[package]
name = "train-carriage-distribution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.2"
itertools = "0.10.3"
rand = "0.8.5"
rand_distr = "0.4.3"
svg = "0.10.0"
